site_name: Yellowbrick
theme: readthedocs
repo_name: GitHub
repo_url: https://github.com/DistrictDataLabs/yellowbrick
site_description: A suite of visual analysis and diagnostic tools for machine learning.
site_author: District Data Labs
copyright: "&copy; 2016 District Data Labs, All Rights Reserved"

pages:
    - "Introduction": index.md
